# Enable Mouse Support
set -g mouse on

# Start Index at 1
set -g base-index 1
setw -g pane-base-index 1

# True Color Support
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# Change Prefix to Ctrl+aunbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g status-position top # Set status bar to top instead of bottom

# Vim Navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Reload Binding
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# TPM (Plugin Manager)
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'

# Configure catppuccin theme
set -g @catppuccin_tmux_flavour 'mocha' # latte, frappe, macchiato, mocha
set -g @catppuccin_window_status_style "rounded"
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

# Initialize TPM (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
